### ISSUE TITLE
Video Streaming Example doesn't not need to use HLS

### ISSUE THREAD

**Issue by daviddias** [ipfs-inactive/old-js-ipfs-website#179]
@jhiesey could you review the Video Streaming Example at https://dev.js.ipfs.io (scroll down to the `What you can build with JS-IPFS` section)? Is it the most exciting thing ever? How would you polish it to blow people's minds in how easy it is to Stream Video with js-ipfs?

**Comment by diasdavid** [comment]
Btw @PedroMiguelSS, the example is not working for me:
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/1211152/46241633-97598480-c3c5-11e8-9e9f-8637d2bdab8c.png">

**Comment by PedroMiguelSS** [comment]
I'm working on it @diasdavid. It's not working on `Firefox` either on `Safari`, but it's working on `Chrome`.

**Comment by PedroMiguelSS** [comment]
@diasdavid, is there a problem to change from `codesandbox` to `codepen`? The only downside of this is that users can't change/edit code directly on our page. If they want to change code they have to open `codepen` by clicking on this link: 
<img width="723" alt="screen shot 2018-10-02 at 14 09 07" src="https://user-images.githubusercontent.com/11461281/46350590-fed53580-c64c-11e8-8466-049fde991ec6.png">

[codepen.io](https://codepen.io/) allows you to edit code on embedded pens but it's a PRO feature.

**Comment by PedroMiguelSS** [comment]
`What you can build` section is currently implemented to work with `codesandbox`. However, video streaming example has some problems on both `Safari` and `Firefox` browsers: 
1. `Firefox`: somehow, the IPFS code is conflicting with `codesandbox` as it throwing internal errors;
2. `Safari`: it doesn't allow to open the `IPFS repo` on embedded examples. `Safari` considers it as a security issue.

### Possible solution 
Change from `codesandbox` to `codepen / jsfiddle / jsbin`. It only solves problem number `1.`, related to `firefox`.
#### Downside
`codepen / jsfiddle / jsbin` code editing feature on embedded pens is a PRO feature.

**Comment by PedroMiguelSS** [comment]
Examples required by @diasdavid:
- [x] Video Streaming
- [ ] Real-time Chat
- [x] Upload files

Real-time Chat is not added yet. Reasons:
- It uses [ipfs-pubsub-room](https://github.com/ipfs-shipyard/ipfs-pubsub-room) and we need a browser build to use it on `codepen`;
- As we need a local `daemon` running I don't think it's a good example as users must have low-effort level to get it running. The examples should work out-of-the-box, i.e., the user shoudln't have to setup or do anything.

Do you really think we should have this example on the website?

**Comment by jhiesey** [comment]
@PedroMiguelSS are you handling the `codesandbox` issue, or would you like me to take a look at what's broken?

@diasdavid one thing I would like to do with video streaming is to add another example using [`videostream`](https://github.com/jhiesey/videostream). The advantage of that module is you don't need to repackage the videos for HLS; instead it works with plain `.mp4` files, which makes for a simpler example. I see that as more of an additional example than a replacement for what's there now.

The main downside with `videostream` is that it can take longer for videos to load since some seeking/searching is necessary to find the video metadata, but that's something that could be fixed by providing some byte offset hints. I'm not sure what that interface ought to look like though.

**Comment by diasdavid** [comment]
@jhiesey yes please! I believe you already did it right? Is there a PR to update that example?
